from enum import Enum

class Typ(Enum):
    KEYWORD = "KEYWORD"
    OPERATOR = "OPERATOR"
    COMMENT = "COMMENT"
    IDENTIFIER = "IDENTIFIER"
    SEPARATOR = "SEPARATOR"
    STRING = "STRING"
    NUMBER = "NUMBER"
    WHITESPACE = "WHITESPACE"
    NEWLINE = "NEWLINE"
    TYPE = "TYPE"
    EOF = "EOF"
    ERR = "ERR"